# Generated by Django 3.2.4 on 2021-06-11 16:51

from django.db import migrations, models
import django.db.models.deletion
import movie.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Genre', max_length=10, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=movie.models.upload_genre_image)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter movie name', max_length=100, unique=True)),
                ('release_year', models.IntegerField(default=movie.models.current_year)),
                ('rating', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=movie.models.upload_movie_image)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.genre')),
            ],
        ),
    ]
