# Generated by Django 3.2.4 on 2021-06-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(help_text='Enter movie name', max_length=100, unique=True),
        ),
    ]
